---
- name: Deploy and Backup Terrain Rentals
  hosts: web_server_group
  become: no
  tasks:
    - name: Ensure backup directory exists
      ansible.builtin.file:
        path: /var/jenkins_home/workspace/I4A_FInalExam/backups
        state: directory
        mode: '0755'

    - name: Backup MySQL database
      ansible.builtin.shell: 
        cmd: docker compose exec mysql-db bash -c "mysqldump -u ratanakdavid -p'Hello@123' A-Ratanakdavid-db > /var/lib/mysql/db_backup.sql"
      args:
        chdir: /var/jenkins_home/workspace/I4A_FInalExam/

    - name: Move backup to workspace
      ansible.builtin.shell: docker compose cp mysql-db:/var/lib/mysql/db_backup.sql ./backups/db_backup.sql
      args:
        chdir: /var/jenkins_home/workspace/I4A_FInalExam/

    - name: Copy JAR to deployment folder
      ansible.builtin.copy:
        src: target/terrain-rentals-0.0.1-SNAPSHOT.jar
        dest: /var/jenkins_home/workspace/I4A_FInalExam/app.jar
        remote_src: no

    - name: Restart application container
      ansible.builtin.shell: docker compose restart terrain-app
      args:
        chdir: /var/jenkins_home/workspace/I4A_FInalExam/